# Generated by Django 4.0 on 2024-02-01 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('care_info', models.TextField(blank=True)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Species',
                'ordering': ['-species'],
            },
        ),
        migrations.CreateModel(
            name='AvailableAdoption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=1)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('information', models.TextField()),
                ('status', models.CharField(choices=[('AVAILABLE TO ADOPT', 'Available to Adopt'), ('LONG TERM FOSTER', 'Long Term Foster'), ('FOSTER TO ADOPT', 'Foster to Adopt'), ('AWAITING FOSTER', 'Awaiting Foster')], default='available to adopt', max_length=30)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='availableforadoption.species')),
            ],
        ),
    ]
